name: Tie-IxHash-FromText
version: 0.01
abstract: A parser for contructing IxHash objects
author: Yung-chung Lin <xern@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Tie::IxHash: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
